name: Deploy Automático Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar atualização via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Entra na pasta do projeto
            cd /var/www/html/PlanoGenerator
            
            # Baixa as informações mais recentes do GitHub sem aplicar
            git fetch --all
            
            # FORÇA o servidor a ficar idêntico ao GitHub descartando alterações locais
            git reset --hard origin/main
            
            # Instala dependências novas caso o package.json tenha mudado
            npm install
            
            # Reinicia o servidor para aplicar mudanças no backend
            pm2 restart PlanoGenerator
            
            echo "Deploy realizado com sucesso!"